name: navigate
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.2.0
  firebase_auth: ^4.1.2
  firebase_storage: ^11.0.5
  cloud_firestore: ^4.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  animated_splash_screen: ^1.3.0
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - images/